[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonky2_maybe_rayon = "0.1.1"
anyhow = "1.0.56"
plonky2 = "0.1.1"
